### ISSUE TITLE
Pomysł na komentarze

### ISSUE THREAD

**Issue by krzyswys** [agh-bit-academy/SummerProject2022#109]
Siema, pomyślałem sobie że fajną rzeczą byłoby okomentowanie poprawnego rozwiązania tak żeby ktoś kto średnio miał styczność z pythonem i programowaniem mógł zrozumieć dlaczego coś zostało napisane w taki a nie inny sposób. Ponieważ na przykład mi dużo problemu sprawiło zadanie z koniem szachowym a garkowe tłumaczenie średnio mnie przekonało. Może nie ma sensu wszystkich opisywać tylko te trudniejsze no ale taki pomysł rzucam, co wy na to?

**Comment by Rusiek** [comment]
Ok, fajne
