### ISSUE TITLE
readstdout.py nie obsługuje pustego outputu

### ISSUE THREAD

**Issue by Nepommuck** [agh-bit-academy/SummerProject2022#14]
def prepare(data, float_type) w readstdout.py zakłada, że output nie jest pusty
![image](https://user-images.githubusercontent.com/100998310/182365180-feb588ab-48df-4be8-a3d0-8351005f55de.png)

Wydaje mi się, że wystarczy zmiana 28 linii z:
    return output[0]

Na np.:
    return output[0] if len(output) > 0 else ""

**Comment by Rusiek** [comment]
Tak rzeczywiście się dzieje, dzięki wielkie za info, postaram się zaraz to zmienić

**Comment by Rusiek** [comment]
Poprawione, zmiany są już na masterze
