### ISSUE TITLE
s3t06 i s3t07 testy

### ISSUE THREAD

**Issue by akarcinski** [agh-bit-academy/SummerProject2022#199]
Problem polega na tym, że to użytkownik generuje tablicę, którą potem zwraca. Zatem sol.py będzie się minimalnie różnił od tego co użytkownik powinien wprowadzić w prog.py a dokładniej funkcje przyjmują inne argumenty bo sol przyjmie tablicę wygenerowaną przez użytkownika a on sam przyjmie liczbę. Ponad to w kodzie będzie 1 linijka różnicy tj. 
array = [randint(1, 1000) for _ in range(n)]
Ja przyjąłem taką konwencję bo nie widzę za bardzo innego sposobu, chyba, że damy użytkownikowi konkretną funkcję do wygenerowania randomowej tablicy z tym, że nie będzie ona randomowa bo my także będziemy musieli jej użyć co się mija z celem.

**Comment by dadamczykk** [comment]
Ja bym zaproponował umieszczenie dwóch funkcji w sol.py, zarówno tej, która będzie podpięta do testów i przyjmowała inne argumenty od funkcji zawartej w prog.py, jak i funkcję wzorcową, która będzie analogiczna do tej z prog.py.
