### ISSUE TITLE
Wczytywanie liczb z klawiatury

### ISSUE THREAD

**Issue by MadMach420** [agh-bit-academy/SummerProject2022#44]
W zadaniach z zestawu drugiego w poleceniach jest napisane, że trzeba wczytywać liczby z klawiatury. Jeżeli faktycznie mamy tak robić to chyba przyda się jakiś moduł, który wpisuje argumenty na stdin. Można też po prostu przekazywać to jako argument do funkcji, ale lepiej żeby wszyscy trzymali się jednego sposobu i żeby była informacja o tym jak mamy robić.

**Comment by Rusiek** [comment]
Zgadzam się, również jestem za tym żeby przekazywać to jako argument i zostanie to poruszone na dzisiejszym spotkaniu, dzięki wskazanie tego problemu
